### ISSUE TITLE
add a method to check if a solana address is valid

### ISSUE THREAD

**Issue by antoineherzog** [cryptoplease/dart-solana-lib#20]
cf.

https://github.com/trustwallet/wallet-core/blob/master/tests/Solana/AddressTests.cpp

TEST(SolanaAddress, isValid) {
    ASSERT_TRUE(Address::isValid("2gVkYWexTHR5Hb2aLeQN3tnngvWzisFKXDUPrgMHpdST"));
    ASSERT_FALSE(Address::isValid(
        "2gVkYWexTHR5Hb2aLeQN3tnngvWzisFKXDUPrgMHpdSl")); // Contains invalid base-58 character
    ASSERT_FALSE(
        Address::isValid("2gVkYWexTHR5Hb2aLeQN3tnngvWzisFKXDUPrgMHpd")); // Is invalid length
}

TEST(SolanaAddress, isValidOnCurve) {
    EXPECT_TRUE(PublicKey(Base58::bitcoin.decode("HzqnaMjWFbK2io6WgV2Z5uBguCBU21RMUS16wsDUHkon"), TWPublicKeyTypeED25519).isValidED25519());
    EXPECT_TRUE(PublicKey(Base58::bitcoin.decode("68io7dTfyeWua1wD1YcCMka4y5iiChceaFRCBjqCM5PK"), TWPublicKeyTypeED25519).isValidED25519());
    EXPECT_TRUE(PublicKey(Base58::bitcoin.decode("Dra34QLFCjxnk8tUNcBwxs6pgb5spF4oseQYF2xn7ABZ"), TWPublicKeyTypeED25519).isValidED25519());
    // negative case
    EXPECT_FALSE(PublicKey(Base58::bitcoin.decode("6X4X1Ae24mkoWeCEpktevySVG9jzeCufut5vtUW3wFrD"), TWPublicKeyTypeED25519).isValidED25519());
    EXPECT_FALSE(PublicKey(Base58::bitcoin.decode("EDNd1ycsydWYwVmrYZvqYazFqwk1QjBgAUKFjBoz1jKP"), TWPublicKeyTypeED25519).isValidED25519());
    EXPECT_FALSE(PublicKey(Base58::bitcoin.decode("ANVCrmRw7Ww7rTFfMbrjApSPXEEcZpBa6YEiBdf98pAf"), TWPublicKeyTypeED25519).isValidED25519());
    EXPECT_FALSE(PublicKey(Base58::bitcoin.decode("AbygL37RheNZv327cMvZPqKYLLkZ6wqWYexRxgNiZyeP"), TWPublicKeyTypeED25519).isValidED25519());
}

**Comment by deimantasa** [comment]
Hi @ookami-kb  - I can see this method was added a while ago into `0.6.0` https://pub.dev/documentation/solana/0.6.0/solana/isValidAddress.html - however is missing in the latest version. 

Was it subsidised by some other method? I couldn't figure it out.

Cheers

**Comment by ookami-kb** [comment]
Hi @deimantasa – it's still there: https://pub.dev/documentation/solana/latest/solana/isValidAddress.html

**Comment by deimantasa** [comment]
Apologies - I've figured it out. Since it's a global, IDE had a hard time finding it. Also `search` was set to the wrong location.

Thank you @ookami-kb for prompt reply!

Cheers
