### ISSUE TITLE
fromMnemonic producing wrong public key?

### ISSUE THREAD

**Issue by pdahlberg** [cryptoplease/dart-solana-lib#26]
### What
I've created a Solana account on mainnet with Phantom, transferred a tiny amount of SOL and exported the mnemonic for it. 
However, the public key I get back from `SolanaWallet.fromMnemoic` does not match the actual pubkey. 

Did I miss something? 
Is it a bug?

**Comment by iharob** [comment]
Hi @pdahlberg. It was indeed a bug. 

We've fixed it and it will be included in our next release soon so you can use it. You can try it from this PR #27

**Comment by pdahlberg** [comment]
Thanks that was quick! 👍
